name: Test

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"
      - "README.md"
  pull_request:
    types: [ready_for_review, synchronize, opened]
    paths-ignore:
      - "docs/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.3]
        laravel: [10.*]
        # exclude:
        #   - php: 8.1
        #     laravel: 11.*

    name: PHP:${{ matrix.php }} / Laravel:${{ matrix.laravel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, pcov, libxml, mbstring, iconv, intl, zip, pdo_sqlite
          tools: composer:v2
          coverage: pcov

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update --dev
          composer update --prefer-stable --no-interaction

      - name: Setup dusk/chrome
        run: vendor/bin/dusk-updater detect --no-interaction

      - name: Run Unit tests
        run: vendor/bin/phpunit --testsuite Unit --cache-directory=".phpunit.cache/code-coverage" --strict-coverage --coverage-clover ./coverage.xml
        env:
          RUNNING_IN_CI: true

      - name: Run Browser tests
        if: success() || failure()
        run: vendor/bin/phpunit --testsuite Browser --cache-directory=".phpunit.cache/code-coverage" --strict-coverage --coverage-clover ./coverage-browser.xml
        env:
          RUNNING_IN_CI: true

      - name: Run Legacy Browser tests
        if: success() || failure()
        run: vendor/bin/phpunit --testsuite LegacyBrowser --cache-directory=".phpunit.cache/code-coverage" --strict-coverage --coverage-clover ./coverage-browserlegacy.xml
        env:
          RUNNING_IN_CI: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml, ./coverage-browserlegacy, ./coverage-browser.xml
          verbose: true